[tool.poetry]
name = "Audio API"
version = "0.1"
description = ""
authors = ["Inigo Allende"]

[tool.poetry.dependencies]
python = "^3.10.12"
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"
python-multipart = "^0.0.6"
pydantic-settings = "^2.1.0"
pydub = "^0.25.1"

